name: Release new version

on:
  release:
    types: [published]

env:
  ONTOLOGY_NAME: pink_annotation_schema
  TAG: ${{ github.ref_name }}

permissions:
  contents: write

jobs:
  release_version:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Create and copy generated files to versions/
        run: |
          mkdir -p versions/${TAG#v}
          cp -f \
              index.md \
              _config.yml \
              versions/${TAG#v}/.

      - name: Push to gh-pages
        run: |
          git config --global user.email "${ONTOLOGY_NAME}@pink.eu"
          git config --global user.name "${ONTOLOGY_NAME}"
          git add versions/${TAG#v}
          if git diff --cached --quiet; then
            echo "No changes to commit for versions/${TAG#v}";
            exit 0;
          fi
          git commit -m "Release version ${TAG#v}"
          git push origin gh-pages
